name: currency_converter
description:
  A versatile Flutter application designed for seamless currency conversion. 
  The app integrates Domain-Driven Design (DDD) for a clean, maintainable architecture 
  and supports multiple environments using Flutter flavors. It features robust database 
  management with Drift, efficient API handling with Chopper, and comprehensive unit testing. 
  Includes pixel-perfect UI based on Figma designs, supports dark mode, and provides 
  an intuitive interface with performance optimizations. Ideal for developers looking 
  to explore advanced Flutter features and architecture best practices.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5
  auto_route: ^9.2.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  kt_dart: ^1.1.0
  rxdart: ^0.28.0
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.1
  internet_connection_checker_plus: ^2.5.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  drift: ^2.19.1+1
  drift_flutter: ^0.1.0
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8
  chopper: ^8.0.1+1
  intl: ^0.19.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  drift_dev: ^2.19.1
  chopper_generator: ^8.0.1
  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
   - assets/svg/
   - assets/launcher_icon/
   - config/
